export const SHOW_OPEN_SPINNER='SHOW_OPEN_SPINNER';
export const HIDE_SPINNER='HIDE_SPINNER';

export const USER_ID_CHANGE='USER_ID_CHANGE';
export const PASSWORD_CHANGE='PASSWORD_CHANGE';
export const SET_ERROR_MESSAGE='SET_ERROR_MESSAGE';
export const ON_LOGIN='ON_LOGIN';
export const ON_LOGOUT='ON_LOGOUT';

export const LOAD_PROBLEMS='LOAD_PROBLEMS';
export const SET_PROBLEMS='SET_PROBLEMS';
export const NEXT_PROBLEMS_PAGE='NEXT_PROBLEMS_PAGE';
export const PREVIOUS_PROBLEMS_PAGE='PREVIOUS_PROBLEMS_PAGE';
export const SET_PROBLEMS_PAGE='SET_PROBLEMS_PAGE';

export const LOAD_QUIZES='LOAD_QUIZES';
export const SET_QUIZES='SET_QUIZES';
export const SET_STARTED_QUIZ='SET_STARTED_QUIZ';
export const SET_STARTED_QUIZ_ANSWERS='SET_STARTED_QUIZ_ANSWERS';
export const SUBMIT_STARTED_QUIZ='SUBMIT_STARTED_QUIZ';
export const NEXT_QUIZES_PAGE='NEXT_QUIZES_PAGE';
export const PREVIOUS_QUIZES_PAGE='PREVIOUS_QUIZES_PAGE';
export const SET_QUIZES_PAGE='SET_QUIZES_PAGE';

export const LOAD_COURSES='LOAD_COURSES';
export const SET_COURSES='SET_COURSES';
export const NEXT_COURSES_PAGE='NEXT_COURSES_PAGE';
export const PREVIOUS_COURSES_PAGE='PREVIOUS_COURSES_PAGE';
export const SET_COURSES_PAGE='SET_COURSES_PAGE';

export const LOAD_USERS='LOAD_USERS';
export const SET_USERS='SET_USERS';
export const NEXT_USERS_PAGE='NEXT_USERS_PAGE';
export const PREVIOUS_USERS_PAGE='PREVIOUS_USERS_PAGE';
export const SET_USERS_PAGE='SET_USERS_PAGE';

export const LOAD_MEETINGS='LOAD_MEETINGS';
export const SET_MEETINGS='SET_MEETINGS';
export const NEXT_MEETINGS_PAGE='NEXT_MEETINGS_PAGE';
export const PREVIOUS_MEETINGS_PAGE='PREVIOUS_MEETINGS_PAGE';
export const SET_MEETINGS_PAGE='SET_MEETINGS_PAGE';
